import type { Metadata } from "next";
import { Fraunces, Barlow } from "next/font/google";
import "../styles/globals.css"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageWrapper from "@/components/PageWrapper";


const fraunces = Fraunces({
  subsets: ["latin"],
  weight: "900",
  variable: "--font-fraunces", 
});


const barlowRegular = Barlow({
  subsets: ["latin"],
  weight: "400", 
  variable: "--font-barlow-regular",
});

const barlowBold = Barlow({
  subsets: ["latin"],
  weight: "700", 
  variable: "--font-barlow-bold",
});

export const metadata: Metadata = {
  title: "Coffeeroasters Subscription Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body
  lang="en"
  className={`${fraunces.variable} ${barlowRegular.variable} ${barlowBold.variable}`}
>
      <Navbar />
      <PageWrapper>{children}</PageWrapper>
      <Footer/>
      </body>
    </html>
  );
}
